### ISSUE TITLE
What is the (new) value of the shifts in the sky spectra for wavelength calibration

### ISSUE THREAD

**Issue by smarttgit** [svalenti/pessto#41]
Stefano/Cosimo - can you confirm the exact value of the wavelength gird (or shifts) that the pipeline now uses when it cross-correlates the observed sky spectrum with the rest frame sky. 

The first SSDR1 used integer shifts of 1 Angstrom for the sky spectrum and minimised the cross-correlation function. I know Stefano changed this - but what is the value ? Is it 0.1 ? 
I can't see it confirmed in writing anywhere. 

I need it for the Release Description and Dave will need to write it into the header for SPEC_SYE

This is what we had previously 

"The library spectrum which produces the minimum in the cross-correlation function is taken as the correct match and this shift is applied. This method limits the precision of the shift to 1 angs, which is roughly 1/4 of a pixel and less than 1/10 of a resolution element. This value of 1Å is recorded in the header as the systematic error in the wavelength calibration (SPEC_SYE)." 

So what is that shift interval now ?

**Comment by cinserra** [comment]
It is 0.1 now

**Comment by smarttgit** [comment]
OK, so the value in the headers should be  SPEC_SYE=0.1 Angs

and I will add this 

"The library spectrum which produces the minimum in the cross-correlation function is taken as the correct match and this shift is applied. This method limits the precision of the shift to 0.1 angs, which is roughly 1/40 of a pixel and less than 1/100 of a resolution element. This value of 0.1Å is recorded in the header as the systematic error in the wavelength calibration (SPEC_SYE)."

**Comment by smarttgit** [comment]
And is it the same for SOFI ?

**Comment by ekankare** [comment]
Wavelength shift is the same 0.1 for SOFI

**Comment by thespacedoctor** [comment]
all spectrum headers have been updated with new value
