### ISSUE TITLE
Pipeline writes out wrong nominal PHOTZP values to the headers 

### ISSUE THREAD

**Issue by smarttgit** [svalenti/pessto#42]
There is a mismatch between the PHOTZP values reported in the paper (Smartt et al. 2015, A&A, Table 4) and those inserted in the EFOSC2 headers.

When there is no calibration available (i.e. outside SDSS DR7, or non-standard fields) the pipeline, or database, should insert the calculated Zeropoint values in Table 4 of Smartt et al. as the values for
PHOTZP.

PHOTZPER is then either the uncertainty on these mags (again as reported in the Table 4) if the night was deemed photometric, or set to 999 if we are unsure.

In SSDR1 there is a mismatch. I have looked more closely at this, and the values in Table 4 appear to be correct. There are two serious discrepancies for r784 and z623 filters. In these cases, the PHOTZP in the header can't be right as it is ~0.4mag fainter than Table 4. I did some other checks with the calculated PHOTZP in the headers in SDSS area and in Figure 15 of the paper. The values in Table 4 appear to be correct.

**Dave checked and the wrong values seemed to be inserted by the pipeline. Pipeline should change as follows**

change all values when we insert a nominal value for the zerpoint. These should be
Filter Old New

U 23.69 23.655

B 25.83 25.755

V 25.88 25.830

R 25.98 25.967

g 25.86 25.897

r 25.27 25.673

i 25.13 25.112

z 24.41 24.777 

The PHOTZPER values in the headers corresponding to nights which are photometric should be the errors in Table 4 of Smartt et al. I checked and they are indeed correct. No changes needed

However we have PHOTZPER=2.0 in the header to denote non-photometric nights. Change this to PHOTZPER=999 to match what we say in the paper.

**Comment by svalenti** [comment]
change done
