### ISSUE TITLE
Issue using cursor on graphics window on Mac

### ISSUE THREAD

**Issue by carys-evans** [svalenti/pessto#59]
I am having an issue using the cursor on the graphics window on a Mac. It seems to work variably, so sometimes it's fine, but sometimes it gets stuck at won't move once it's on the graphics window.

A video demonstrating the issue can be found here:
https://cf-my.sharepoint.com/:f:/g/personal/evanscr8_cardiff_ac_uk/Etzklvf_5VZAvQbcDMKOgZEBY2UVQgzhUqhvObBS3PRulg?e=XywCdF

Everything else seems to run smoothly, I just am not able to complete the interactive steps that require the use of the cursor.

**Comment by temuller** [comment]
@carys-evans that is odd. I'll try to see if I can find a solution. In the meantime, can you post this on https://github.com/iraf-community/iraf/issues? They might have a better idea of what is happening.

**Comment by carys-evans** [comment]
@temuller Thank you - I have posted the issue on the iraf github too!

**Comment by carys-evans** [comment]
@temuller Thank you - I have posted the issue on the iraf github too!

**Comment by carys-evans** [comment]
@temuller Thank you - I have posted the issue on the iraf github too!

**Comment by temuller** [comment]
Solved using the workaround from https://github.com/iraf-community/pyraf/issues/107.
Read the [REAME.md](https://github.com/svalenti/pessto/blob/master/README.md#fix-cursor-issue-for-macos) for the solution.
